environment:
  VERSION_SUFFIX: alpha
  FRAMEWORK: netcoreapp2.2
  PROJECT: j2s
  RID: win-x64
  
version: 0.0.1-$(VERSION_SUFFIX){build}

# branches to build
branches:
  only:
  - master

# Do not build on tags (GitHub and BitBucket)
# abakumov-v: Because tags created by GitHub Release deployment configuration
skip_tags: true

image: 
  - Visual Studio 2019
  - Ubuntu1804

configuration: Release

# Patch .NET Core/Standard *.csproj files for versioning:
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

# restore Nuget packages before build:
before_build:
- dotnet restore

build_script:
  - ps: dotnet publish $env:PROJECT -c $env:configuration -f $env:FRAMEWORK -r $env:RID --self-contained false

#after_build:
#  - ps: 

artifacts:
 - path: '$(PROJECT)\bin\$(configuration)\$(FRAMEWORK)\$(RID)\*.*'
   name: ConsoleApplication

for:
-
  matrix:
    only:
      - image: Visual Studio 2019

  deploy:
   - provider: GitHub
     name: production-GitHub
     description: ''
     artifact: /.*\.zip/
     draft: true
     prerelease: true # TODO: (VERSION_SUFFIX != string.empty) ? true : false
     auth_token:
       secure: cXU/5uMu5hDP4h2I7NTHUQ4qaDY67P9hDwNVe2hwEijidAJXQe6zX1f1CInMYOcV
     on:
       branch: master                # release from master branch only
       #appveyor_repo_tag: true       # deploy on tag push only 
  
# send notification to Slack about build results
notifications:
 - provider: Slack
   incoming_webhook: https://hooks.slack.com/services/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
   channel: releases
   on_build_success: true
   on_build_failure: true
   on_build_status_changed: false
